name: Olake UI Releaser

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
      environment:
        description: "Environment to build (master, staging, dev)"
        required: true

jobs:
  build_and_release:
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master')
    name: Build and Release Olake UI
    uses: ./.github/workflows/build-and-release.yml
    with:
      environment: master
      version: ${{ github.event.inputs.version || github.event.release.tag_name }}
    secrets: inherit
